<a href="https://colab.research.google.com/github/sbolla777/2025-Summer-Project/blob/main/Notes/Module-3/python_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python Notes**

---

## Basics

**Keywords** are words which has special meaning and predefined functionality. Thus, these words cannot be used for any other purpose, such as variable or function names. In the code below, some important keywords (and, def, if, elif, else, for) are demonstrated. The full list of keywords is also provided.

In [ ]:
import keyword
def my_function():
  for x in range(1, 6):
    if x > 1 and x < 5:
      print("middle")
    elif x == 1:
      print("beginning")
    else:
      print("end")
my_function()
print(keyword.kwlist)

beginning
middle
middle
middle
end
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

An **identifier** is a user-created name given to a variable, function, class, or module in order to identify and use it, as shown below. The function is given the identifier 'sum' and we define its parameter variables as 'x' and 'y'. By giving these objects names, we can use them when calling the function and printing the sum value.

In [ ]:
def calc_sum(x, y):
  print(x + y)
calc_sum(10, 7)

17

In Python, **comments** are written using hashtags or three single/double quotes. Comments are often used to make the code more readable and explain difficult sections. Hashtags are used for short, single line notes, while three quotes are for multi-line explanations. Since the function name 'new_function' below does not explain its purpose, a comment can do so instead. In the rest of the code, single line comments explain the purpose of a certain line

In [ ]:
'''The function below finds the square of the sum of two numbers x and y.
In other words, it prints (x+y)^2'''
def new_function(x, y):
  sum = x + y
  print(sum*sum)
new_function(-1, 1) # this function call will print the result 0
# new function(2, 5) this function call will not print anything

0

**Statements** are basic instructions which the interpreter can execute that we write to complete a task. Examples of statements include imports, printing, assignment, conditionals, loops. Statements are usually a single line, but can be extended using the character '\\'.

In [ ]:
# an import statement
import keyword
# assignment stament continued to two lines
x = 1 + 2 + \
2 + 4 + 5 + 6
# conditional statement
if(x == 20):
  print("yay!") # print statement
# looping statementfor x in range(1, 2):
  print("no!") # print statement

yay!
no!

In Python, **indentation** is used to define blocks of code. This is how the  interpreter knows that code belongs in the body of an if-statement, within a function definition, or in a loop. Failing to indent will cause an indentation error.

In [ ]:
x = 4
while x > 1:
  x = x - 1
  print(x) # since the loop was indented correctly, "3 2 1" will be printed

y = 4
while y > 1:
  y = y - 1
print(y) # since the loop is not indented, the same code will print just "1"

3
2
1
1

A **docstring** is the first line(s) of a function, class, or module and documents the usage and purpose in three quotes. Unlike a regular comment, docstrings are stored as an attribute of their associated object and can be accessed.

In [ ]:
def mult(x, y):
  """
  Multiplies two numbers and returns the product.

  Args:
      x: first number
      y: second number

  Returns:
       The product the the two parameters
  """
  return x*y
prod = mult(5, 2)
print(prod)
print(mult.__doc__) # we can access the docstring with this call

10

  Multiplies two numbers and returns the product.

  Args:
      x: first number
      y: second number

  Returns:
       The product the the two parameters

**Strings** in Python are indicated through single or double quotes. For multi-line strings, three quotes can be used.

We can find the length of a string using the len() function and search for certain characters within it using the keyword 'in'.

Strings have both **forward** and **backward** **indexing**. In forward indexing the first character is in position 0 and can be accessed with str[0], the second character is in position 1, and so on. For backward indexing, the last char character is in position -1, the second to last is in -2, and this continues in decreasing values.

Using **string** **slicing**, we can get a range of characters within a string. For the first 5 characters,we can use str[:5]. str[5:], however, will get the characters from position 5 to the end of the string. To retrieve the characters from position 1 to position 5, we use str[1,6], since the end of the range is not inclusive. Splicing can also be done with backward indexing.

To modify a string, the replace(str1, str2) method can be used to replace all occurences of str1 in the string with str2. The string can also be divided around a certain phrase using the split(str) method. Furthermore, the upper() and lower() functions are used to convert the entire string to uppercase or lowercase, respectively. The strip() function is used to remove all whitespace from the beginning and end of a string. To conjoin two strings together, we simply use to addition operatir '+'.

In [ ]:
str = "  hello, world  ".title()
print(str)
str1 = "Say" +  str[:7]
# this will print "Say  Hello," the first five characters with "Say" concatenated
print(str1)
str2 = str[-7:-1]
# since we used backward indexing, this will print "World"
print(str2)
str = str.replace("World", "Everyone")
# due to the replace function, "  Hello, Everyone  " will be printed
print(str)
str = str.lower()
# the lowercase version "  hello, everyone  " will be printed
print(str)
str = str.strip()
# without whitespaces, "hello, everyone" will be printed
print(str)
split_str = str.split(",")
# the string has been split around the comma and stripped, so the second part "everyone" will be printed
print(split_str[1].strip())

  Hello, World
Say  Hello
World
  Hello, Everyone
  hello, everyone
hello, everyone
everyone

# Datatypes

Python **lists** are used to store items in an ordered, indexed variable that can be modified. Like strings, lists have backward and forward indexing. However, instead of accessing characters, we can access whichever object was placed at the index. In order to find an item within the list, the method index(item) will return the first index where the item occurs. Or, the count(item) method will sum the number of occurences of the item in the list.

Lists can also be **sliced**, using a similar format to strings. To get the first five elements of a list, we would use list[:5]. The last four elements would be list[-5:]. The call list[3:7] would get the elements from the third position to the sixth.

In order to add an item to a list, we use the append(item) function. To put an element in a specific position, the insert(index, item) call is used. Conversely, the remove(item) function deletes the first occurence of the element. To empty the entire list, the clear() function can be utilized. To reverse the contents of the list, we use the reverse() function, and to sort the list we can use the sort() function. To join two different lists either the '+' operator or the extend(list2) function can be used.

Characteristics of the list can also be obtained using functions. The number of total elements in a list is found with the len(list) function. The maximum and minimum values are calculated with the max(list) and min(list) functions, respectively. For lists comprised of only ints or floats, the sum(list) function finds the sum of all values. To copy the list we can use copy(), and to create a sorted copy of the list we use sorted(list).

To loop through a list, our for loop must use "for item in list" as its header. Then, each item can be modified or used within the loop's body.

In [ ]:
# the list below is the grades of a class on a math test
grades = [85, 23, 90, 98, 100, 55, 67, 48, 67, 88, 92, 92, 45, 77, 75, 74, 75]
# the call below shows the number of grades, or the number of students
num = len(grades)
print(f"There are {num} students in the class")
# someone joined the class late and had to make up the exam
grades.append(95)
# the teacher gave fifteen points to the person with the lowest grade
lowest = min(grades)
grades.remove(lowest)
grades.append(lowest + 15)
# the teacher wishes to find the five highest scores
grades.sort()
highest = grades[-5:]
print(f"The five highest grades on the test were {highest}")
# the teacher wants to find the average score
avg = sum(grades)/num
print(f"The average score on the test was {avg}")
# the teacher wishes to award points based on how low a student scored, with 0 points for the highest and 16 for the lowest
grades.reverse()
bonus = 0
new_grades = []
for grade in grades:
  new_grades.append(grade + bonus)
  bonus += 1
# display the new grades
print(f"Here are the new grades: {new_grades}")
# another class is also reporting their grades
other_grades = [45, 43, 55, 66]
all_grades = new_grades + other_grades
# display the grades
print(f"Here are all the grades: {all_grades}")

There are 17 students in the class
The five highest grades on the test were [92, 92, 95, 98, 100]
The average score on the test was 80.05882352941177
Here are the new grades: [100, 99, 97, 95, 96, 95, 94, 92, 85, 84, 85, 85, 79, 80, 69, 63, 61, 55]
Here are all the grades: [100, 99, 97, 95, 96, 95, 94, 92, 85, 84, 85, 85, 79, 80, 69, 63, 61, 55, 45, 43, 55, 66]

**Tuples** also store multiple, ordered values in a single variable. However, tuples cannot be changed after it has been created, unlike lists. We can check if an item is in the tuple using the 'in' operator, like with lists and strings.

Like lists, the elements of a tuple can be accessed with forward and backward indexing. Additionally, tuples can be sliced to retrieve smaller tuples. The first element of a tuple would be tuple[0] and the call tuple[-5:] would get the last five elements.

Tuples cannot be changed, so modifying them in any way is difficult. However, we can convert the tuple to a list using the list(tuple) function and change the list as necessary. the tuple can be converted back with tuple(list) call and assigned back to the orignal variable. While individual items cannot be added to a tuple, two tuples can be joined together with the '+' operator and assigned to the variable. We can also multiply tuples to increase the instances of each element; for, example, if we perform tuple * 2, each element inside the tuple will now be repeated.

Like with lists, the index(item) function will find the index of the first occurence of the element in the tuple and count(item) will return the number of instances. Additionally, the len(tuple), max(tuple), and min(tuple) will return lengt, maximum, and minimum values, respectively. With a tuple of all numeric values, the sum(tuple) call will return the sum of all values within it. The sorted(tuple) function will return a sorted version of the tuple.

Looping over tuples is very similar to looping over lists, our header will be: for item in tuple. Through this, we can access but not directly change the tuple's values within the loop's body.

In [ ]:
# consider this collection of items in a grocery cart
basket = ("apple", "apple", "frozen pizza", "cereal", "milk", "orange juice", "eggs", "eggs", "bread")
# here are the associated prices
prices = (1.5, 1.5, 5, 3, 4, 3, 10, 10, 2)
# find the full cost of the cart
total = sum(prices)
print(f"The full cost is {total}")
# the customer must buy mre since there is an extra visitor in her home
basket *= 2
prices *= 2
# all animal products are now taxed 50%
price_list = list(prices)
price_list.remove(5)
price_list.remove(5)
price_list.remove(4)
price_list.remove(4)
price_list.remove(10)
price_list.remove(10)
price_list.remove(10)
price_list.remove(10)
price_list.extend([5*1.5, 5*1.5, 4*1.5, 4*1.5, 15, 15, 15, 15])
# the customer is concerned about how many  items are above $5
count = 0
for item in price_list:
  if item > 5:
    count += 1
print(f"{count} items are above $5")

The full cost is 40.0
8 items are above $5

Like lists, **sets** can have elements added and removed. Unlike tuples and lists, however, this data type is also unordered and does not allow for duplicate values.

To add an item to a set, we can use add(item). The call update(set2) adds a second set's elements to the original set. To remove an item that is defintely in the list the method remove(item) can be used. Otherwise, the call discard(item) will not raise any errors. pop() can be used to remove and obtain a random item from the set. When emptying the entire set, the clear() function can be called.

Several operations on sets from set theory are also built into Python such as **union**(other_sets), **intersection**(other_sets), and **difference**(other_sets). Each of these function produces a new set with the given operation performed between the first and second sets. The **symmetric_difference**(set2) method returns a new set which contains all elements in either set but not in intersection. To check whether a set is a **superset**, **subset**, or **disjoint** of another set, we use the issuperset(set2), issubset(set2), and isdisjoint(set2) methods.

Like with the previous data types, the len(set) function can be used to find the sumber of items in the set. max(set) and min(set) return the maximum and mininum of the set. Furthermore, sorted(set) returns a sorted version of the set.

Looping over tuples is also the same as for the other types, and our header will be: for item in set. We can perform methods using the item and other set operations in the body.

In [ ]:
# the students athletes at a highschool
tennis = {"Aiden", "Max", "Carly", "Lily", "Zara", "Ethan", "Frankie", "Rose", "Taylor", "Riley", "Avery"}
soccer = {"Cassie", "Sarah", "Jennie", "Jacob", "Timothy", "River", "Max", "Avery", "Lily", "Jackson"}
track = {"Jacob", "Max", "Lily", "Jackson", "Marie", "Megan", "Ben", "John", "Aaron", "Eric", "Christina", "April"}
# which students play both tennis and run track?
both = tennis.intersection(track)
print(f"These students play both tennis and track: {both}")
# which students play only one sport?
one = tennis.symmetric_difference(track.union(soccer))
print(f"These students play only one sport: {one}")
# how many student athletes are there?
athletes = tennis.union(soccer, track)
print(f"There are {len(athletes)} students athletes")
# three students are friends outside of school. do they all play tennis?
friends = {"Max", "Lily", "Taylor"}
if friends.issubset(tennis):
  print("Yes, they all play tennis")
# do any of the friends play soccer?
if not friends.isdisjoint(soccer):
  print("Yes, they do")

These students play both tennis and track: {'Max', 'Lily'}
These students play only one sport: {'Jackson', 'Aaron', 'Taylor', 'John', 'Cassie', 'Carly', 'Sarah', 'River', 'Christina', 'Timothy', 'Megan', 'Jennie', 'Marie', 'April', 'Ben', 'Ethan', 'Rose', 'Eric', 'Frankie', 'Riley', 'Zara', 'Jacob', 'Aiden'}
There are 26 students athletes
Yes, they all play tennis
Yes, they do

**Dictionaries**, like sets, do not allow for duplicates and can be changed. Unlike sets, however, they are ordered and have indices for access. This data type is comprised of key:value pairs and written in this format as well. To access a value in the dictionary, we can use dictionary[key] or the dictionary.get(key) method. The keys() method will provide a list of all keys if they are not known. For the values, we can call values(), and for a tuple list of each pair there is items().

To modify the value associated with a key, either the square brackets can be used like dictionary[key] = new_value. Otherwise, the update({key:value}) call will perform the same change. The same two methods will also add a new key:value pair if the key is not already present within the dictionary. To remove a key:value pair, the pop(key) method will both remove the pair and return the associated value. Otherwise, the popItem() call removes and returns the last inserted pair. To empty the entire structure, we can use the clear() method. The copy() method, conversely, will create a copy of the dictionary to set another variable to.

Like with the other datasets, the len(dictionary) and sorted(dictionary) will give the number of pairs and provide a sorted list of keys, respectively. To create an empty dictionary, a copy, or convert another data structure into a dictionary, we can use dict(object). As always, the del keyword will delete any entire dictionary object.

The format for looping over dictionaries is slightly different. We can either loop directly over the dictionary, which is equivalent to looping over its keys or over dictionary.keys(). Otherwise, we can loop directly over the values with values() or the key:value pairs entirely with items(). Depending on the purpose of the loop, different functions can be used in the header.

In [ ]:
import json
# opening iris json data
with open('iris.json', 'r') as file:
    iris = json.load(file)
# find the average petal length of versicolor irises
sumlength = 0
num = 0
for flower in iris:
  if flower['species'] == 'versicolor':
    sumlength += flower.get('petalLength')
    num += 1
print(f"The average petal length of versicolor irises is {sumlength/num}")
# opening webster dictionary data
with open('dictionary.json', 'r') as file:
    dictionary = json.load(file)
# how many words are in this dictionary?
print(f"There are {len(dictionary)} words in this dictionary")
# find the meaning of the longest word
longest = ""
for word in dictionary:
  if len(word) > len(longest):
    longest = word
print(f"The longest word is {longest}")
print(f"Its definition is: {dictionary.get(longest)}")
# remove the longest word from the dictionary
dictionary.pop(longest)
# find and print every word alphabetically before "abacus" in the dictionary
keylist = sorted(dictionary)
for key in keylist:
  if key < "abacus":
    print(key)

The average petal length of versicolor irises is 4.26
There are 102217 words in this dictionary
The longest word is vickers-maxim automatic machine gun
Its definition is: An automatic machine gun in which the mechanism is worked by the recoil, assisted by the pressure of gases from the muzzle, which expand in a gas chamber against a disk attached to the end of the barrel, thus moving the latter to the rear with increased recoil, and against the front wall of the gas chamber, checking the recoil of the system.
-
--
------
-able
-ably
-ana
-ance
-ancy
-ant
-arch
-ard
-art
-ate
-ation
-blast
-derm
-dom
-ed
-ee
-en
-ence
-ency
-ent
-er
-escent
-esque
-ess
-est
-et
-ferous
-ful
-fy
-gen
-genous
-gerous
-gram
-graph
-graphy
-grave
-head
-hood
-ible
-ic
-ics
-ide
-in
-ine
-ing
-ion
-ise
-ish
-ism
-ist
-ite
-itis
-ive
-ize
-kin
-less
-let
-ling
-lite
-lith
-logy
-ly
-mancy
-ment
-mere
-meter
-metry
-mo
-morphous
-ness
-ock
-oid
-ol
-oma
-one
-or
-ory
-ose
-our
-ous
-plastic
-plasty
-pod
-poda
-ric
-s
-scope
-ship
-some
-ster
-type
-uret
-ward
-wards
-ways
-yl
a
a b c
a cappella
a cheval
a fortiori
a mensa et thoro
a posteriori
a priori
a-
a-good
a-mornings
a-sea
a-tiptoe
aam
aard-vark
aard-wolf
aaronic
aaronical
ab
ab-
abaca
abacinate
abacination
abaciscus
abacist
aback
abactinal
abaction
abactor
abaculus

# Operators

**Arithmetic** operators are used to perform mathematical operation using numbers. This includes addition ('**+**'), subtraction ('**-**'), multiplication ('**\***'), and division ('**/**'). Less straightforward operators are the modulo operation ('**%**'), floor division ('**//**'), and exponents ('**\****'). The modulo operation finds the remainder of a division calculation. Conversely, floor division discards the remainder and returns just the integer result.

In [ ]:
print(5 + 8)
print(6 - 3)
print(2 * 10)
print(8 / 2)
print(13 % 4)
print(8 // 5)
print(2 ** 3)

13
3
20
4.0
1
1
8

To compare two different values, we use **comparison** operators. These operators check whether the condition holds and returns a boolean for its truth value. The '**==**' operator checks if two values are equal, '**!=**' checks whether they are not equal, '**>**' checks if the first value is greater, and '**<**' checks if the second value is greater. For a broader range of functionality, '**<=**' and '**>=**' checks if the first value is less than or equal and greater than or equal to the second value, respectively.

In [ ]:
if 5 < 2:
  print("True")
  print("5 is less than 2")
else:
  print("False")
  print("5 is not less than 2")
print(5<=5)
print(5!=5)
if 0 == 0:
  print("0 is 0")

False
5 is not less than 2
True
False
0 is 0

Using **logical** operators, we can combine two conditional statements, like the ones created using comparison operators. The **and** operator returns true if both staments are true and false otherwise, the **or** operator only returns true if at least one statement is true, and the **not** operator returns the opposite boolean value of the conditional statement it is applied to.

In [ ]:
if 3 >= 2 and 3 <= 4:
  print("True")
if 0 != 0 or 1 == 1:
  print("Or holds")
print(not True)

True
Or holds
False

The **membership** operator '**in**' returns true if the given value is found in the object. Conversely, the '**not in**' operator only returns true if the given value cannot be found in the object.

**Identity** operators check if two objects are the same. The operator '**is**' returns true if the both are the same object and '**is not**' returns true if they are not.

In [ ]:
fruits = ["apple", "orange", "pear", "banana", "peach"]
print("apple" in fruits)
print("pineapple" not in fruits)
if type(fruits) is list:
  print("fruits is a list")
if fruits is not fruits:
  print("0 is not an int")

True
True
fruits is a list

**Bitwise** operators are used to perform operations in base 2, using bits. The '**&**' operator compares each bit in two given numbers and sets each result bit to 1 if both bits are also 1 at that position. The '**|**' operator sets each reult bit to 1 if either of the values' bit is 1 at that location. Similarly, the '**^**' operator sets each reult bit to 1 if only one of the values' bit is 1 at that position. The '**~**' operator simply flips all the bits into their oppposite value. The leftward shift operator '**<<**' shifts all the bits to the left by a given amount, filling in the spaces with zeroes. This is equivalent to multiplying the value by a power of two. Meanwhile, the rightward shift '**>>**' shifts the bits to the right and divides the value by some power of two.

In [ ]:
print(20 & 15)
print(5 | 4)
print(10 ^ 2)
print(~16)
print(3 << 2)
print(3 * 2**2)
print(8 >> 1)
print(8 / 2)

4
5
8
-17
12
12
4
4.0

The most basic **assignment** operator is '**=**'. Assignment operators can also combine with arithmetic operators to perform a mathematic operation and assign the value back to a variable. Additionally, bitwise operators can also be combined with the assignment '**=**' to perform a bitwise operation and assign the new value.

In [ ]:
count = 1
for i in range(1, 4):
  count *= i
print(count)
count %= 4
print(count)
count **= 4
print(count)
count //= 3
print(count)
count <<= 2
print(count)
count ^= 2
print(count)

6
2
16
5
20
22

# Functions

Python functions are constructed using the '**def**' keyword. Each function is assigned a name to be called again and, within parentheses, the **parameters** you must pass into it. The header of a function is always: def function_name(args):. Within the function body, we can add the code block which uses and changes the parameters as necessary. The body of the function can also contain a **return** value, which will be produced as a final result of the function call. Functions are a way of simplifying code and reducing redundancy, so this should be code that will either be used multiple times or condenses othewise tedious work.

Functions can have paramers of any type, such as lists, dictionaries, tuples, sets, floats, strings, etc. The type does not need to be declared, however the methods inside the function must be consistent with the type to avoid errors.

The methods we have previously used, such as copy(), union(set), and index(list), are all built-in functions for python. For user-defined functions, we must use the format specified above. The ability to define our own functions expands the ablity of what our code can do and greatly simplifies longer projects.

In [ ]:
# this function cubes the parameter
def cube(num):
  return num**3

print(cube(8))
print(cube(-4))

#this function says hello to the given name
def hello (name):
  print(f"Hello, {name}!")

hello("World")
hello("Everyone")
hello("You")
hello("Sreeja")

# this function prints words and their meanings
def print_dictionary(dictionary):
  for word in dictionary:
    print(f"{word}: {dictionary.get(word)}")

dictionary2 = {}
# the new dictionary is a part of the original one
for key in keylist[200:205]:
  dictionary2[key] = dictionary.get(key)

print_dictionary(dictionary2)

512
-64
Hello, World!
Hello, Everyone!
Hello, You!
Hello, Sreeja!
abdicant: Abdicating; renouncing; -- followed by of. Monks abdicant of their orders. Whitlock.

One who abdicates. Smart.
abdicate: 1. To surrender or relinquish, as sovereign power; to withdraw definitely from filling or exercising, as a high office, station, dignity; as, to abdicate the throne, the crown, the papacy. Note: The word abdicate was held to mean, in the case of James II., to abandon without a formal surrender. The cross-bearers abdicated their service. Gibbon. 2. To renounce; to relinquish; -- said of authority, a trust, duty, right, etc. He abdicates all right to be his own governor. Burke. The understanding abdicates its functions. Froude. 3. To reject; to cast off. [Obs.] Bp. Hall. 4. (Civil Law)  To disclaim and expel from the family, as a father his child; to disown; to disinherit. Syn. -- To give up; quit; vacate; relinquish; forsake; abandon; resign; renounce; desert. -- To Abdicate, Resign. Abdicate commonly expresses the act of a monarch in voluntary and formally yielding up sovereign authority; as, to abdicate the government. Resign is applied to the act of any person, high or low, who gives back an office or trust into the hands of him who conferred it. Thus, a minister resigns, a military officer resigns, a clerk resigns. The expression, "The king resigned his crown," sometimes occurs in our later literature, implying that he held it from his people. -- There are other senses of resign which are not here brought into view.

To relinquish or renounce a throne, or other high office or dignity. Though a king may abdicate for his own person, he cannot abdicate for the monarchy. Burke.
abdication: The act of abdicating; the renunciation of a high office, dignity, or trust, by its holder; commonly the voluntary renunciation of sovereign power; as, abdication of the throne, government, power, authority.
abdicative: Causing, or implying, abdication. [R.] Bailey.
abdicator: One who abdicates.

If the number of parameters passed into the function changes or is unknown, the '**\***' symbol is used to indicate a **tuple** of arguements. The format def func_name(*args): passes a tuple called arg whose elemts can be accessed using indexing and tuple methods.

To pass an unknown number of arguements in the key = value format, as a dictionary, the '**\****' symbol can be used. These are called **keyword arguements**. The header will have the format: def func_name (**kwargs):, and the arguements can be accessed using dictionary methods.

In [ ]:
def print_people(*people):
  for person in people:
    print(person)

# as shown below, a varying amount of parameters can be passsed into the function
print_people("Aiden", "Max", "Carly")
print_people("Lily", "Zara", "Ethan", "Frankie", "Rose", "Taylor", "Riley", "Avery")

def print_info(**info):
  for key, value in info.items():
    print(f"{key}: {value}")

# the call passes a varying amount of parameters in key = value format
print_info(me = "Riley", mom = "Susan", dad = "Conner", sister = "Sarah", brother = "Ethan", aunt = "Karen", uncle = "Joe")
print_info(me = "Frankie", mom = "Janet", brother = "Max")

Aiden
Max
Carly
Lily
Zara
Ethan
Frankie
Rose
Taylor
Riley
Avery
me: Riley
mom: Susan
dad: Conner
sister: Sarah
brother: Ethan
aunt: Karen
uncle: Joe
me: Frankie
mom: Janet
brother: Max

**Lambda functions** are small, anonymous functions that use the **lambda** keyword in their definition. As indicated before, they have no name and can only have one expression within their 'body.' These functions are used to simplify a block of code that is only needed once or for one-line functions. They use the format lambda args: expression.

In [ ]:
# the lambda function below finds the square of the sum of its parameters
sum_square = lambda *args: sum(args)**2
print(sum_square(1, 2, 3, 4, 5))

225

The **map**() function is an in-built Python function that applies a function with a single arguement and return value to every item in an object. The object must be able to be looped over, or **iterable**. Common iterable objects are lists, sets, tuples, dictionaries, etc. The format of the function call is map(function, iterable)

The **filter**() function also applies a function to every element in an iterable object, but the function must return a boolean value. If the function returns **True**, the item is kept, otherwise it is discarded. The final return value of the filter(function, iterable) call is a version of the iterable object with only the items that returned true.

**reduce**(), unlike the other two in-build functions, returns a single value. It also must be imported using the functools module. This function is applied cumulatively to reduce that iterable to a single meaningful value. The function call is reduce(function, iterable), and the function must take two parameters and return a single value.

We have used the **sorted**() method on the list, set, dictionary, and tuple datatypes. The function can take only one arguement, the iterable type, with the call sorted(iterable). However, to sort by a specific parameter, we can also pass a function to sort by in the key = function format. To sort by something specific, the call sorted(iterable, key = function) is used. We can also pass the 'reverse = True/False' arguement into the call to indicate whether the sort should be ascending or descending; the default is False or ascending.

For all of the functions mentioned in the above methods, we can use lambda to simplify the code. These are the perfect applications for lambda functions since the functions required have only one return value and are simple.

In [ ]:
from functools import reduce
grades2 = [85, 23, 90, 98, 100, 55, 67, 48, 67, 88, 92, 92, 45, 77, 75, 7]
# the map function increases each grade by 5 points
grades3 = map(lambda x: x + 5, grades)
# the filter function finds all grades above an 80
grades4 = filter(lambda x: x > 80, grades)
# the reduce function finds the sum of all grades
sumgrades = reduce(lambda x, y: x + y, grades)
mean = sumgrades/len(grades)
print(f"The average grade is {mean}")
peoplelist = ["Jacob", "Max", "Lily", "Jackson", "Marie", "Megan", "Ben", "John", "Aaron", "Eric", "Christina", "April"]
# the first sorted call sorts alphabetically
print(sorted(peoplelist))
# the second call sorts based on name length
print(sorted(peoplelist, key = lambda x: len(x)))

The average grade is 69.3125
['Aaron', 'April', 'Ben', 'Christina', 'Eric', 'Jackson', 'Jacob', 'John', 'Lily', 'Marie', 'Max', 'Megan']
['Max', 'Ben', 'Lily', 'John', 'Eric', 'Jacob', 'Marie', 'Megan', 'Aaron', 'April', 'Jackson', 'Christina']

To modify a function or add to its behavior without changing existing code, we can use a **decorator** function. These functions take other functions as a parameter and returns a new function with the new functionality added to it. Within the body of the decorator is a nested wrapper function which changes the parameter function's behavior.

To change a function using a decorator, we can either use the normal syntax, func_name = decorator_name(func_name), or write @decorator_name before the function being modified.

In [ ]:
# this decorator modifies the function by printing a phrase before it is called
def intro(func):
  def wrapper():
    print(f"Hello, Everyone!")
    func()
  return wrapper

# this modifies the greeting function using the intro decorator
@intro
def greeting():
  print("My name is Sreeja!")

# this will now print the phrase indicated in the decorator before greeting()
greeting()

# this decorator adds 5 to the return value of the parameter function
def add_5(func):
  def wrapper(x):
    return func(x) + 5
  return wrapper

# this function squares the arguement value
def square(x):
  return x*x

# by passing the square function into add_5, we modify it and assign it to the square_add5 var
square_add5 = add_5(square)
print(square_add5(5))

# this variable is still assigned to the pure square function, so this should print the square
print(square(5))

Hello, Everyone!
My name is Sreeja!
30
25

# Files

**Files** can accessed using the open("path", "mode") function where the specific pathname must be written out to open the file without errors. The possible modles are **"r"** or read, **"w"** or write, **"a"** or append, **"c"** or create, **"t"** or text, and **"b"** or binary. Read and text or **"rt"** is the default mode if not specified. If you want to modify, add to the file, create a new file that does not exist, or view an image, the other modes can be used. The first four modes can be combined with the last to specify the actions that you wish to perform and type of the file.

Another way to access a file, which can reduce possible errors, is using the '**with** keyword. Using this keyword, we can put all file operations inside the body of the header: '**with open("pathname", "mode") as file:**. If opening the file without this keyword and format, we must use the close() method on the file after it has no more use to avoid errors.

While files with the .txt extension can be directly read and modified after being opened, .json, .csv, .pdf, and others may require additional modules and function calls.

In [ ]:
file = open("sales_historical_cars.csv", "wt")
file.close()
with open("sales_historical_cars.csv", "r") as file2:
  print(file2.name)

sales_historical_cars.csv

To **read** a file we can use the method read(). This returns the text of the file as a string, which we can assign to a new variable to use or print directly. For more specific reading, we can use the method readline() to read and return the string of a single line. For the all of the lines in a file, the readlines() call will create a list of the lines as strings.

In [ ]:
with open("federalist_papers.txt") as file3:
  lines = file3.readlines()
  for line in lines[10:15]:
    print(line)

with open("federalist_papers.txt") as file4:
  for i in range(15):
    line = file4.readline()
    if i > 9:
      print(line)

Title: The Federalist Papers



Author: Alexander Hamilton

        John Jay

        James Madison

Title: The Federalist Papers



Author: Alexander Hamilton

        John Jay

        James Madison

To modify an existing file, we always use the **write()** call. If in **write** mode, this will overwite existing text. If in **append** mode, the call will add the given text to the end of the document without editing the rest.

To create a new file that definely does not exist, we simply use the open() call with a new pathname and on the **create** mode. Otherwise, we can open on write or append mode to avoid errors and possibly modify this new file later on.

In [ ]:
with open("authors.txt", "a") as file5:
  for line in lines[10:15]:
    file5.write(line)
with open ("authors.txt", "r") as file6:
  print(file6.read())

Title: The Federalist Papers

Author: Alexander Hamilton
        John Jay
        James Madison

To check the **existence** of a file or to **remove** it, we must import the **os** module. Using this module, we can call os.remove("pathname") to delete the file. The function os.path.exists("pathname") will return true only if the file exists, which will verify it exists.

In [ ]:
import os
open("del_file.txt", "w")
if os.path.exists("del_file.txt"):
  os.remove("del_file.txt")
else:
  print("The file does not exist")
if os.path.exists("del_file.txt"):
  print("Delete Failed")
else:
  print("File Deleted")

File Deleted

Like with .json files, to perform functions on .csv files, we must import the **csv** module. To open a csv file, we must add **newline = ' '** inside the open() function call. To view the file, we must assign csv.reader(file_name) to a variable. This variable will be a list that an be looped through and viewed. To write to the file instead, we use **'w'** or **'a'** mode and set the result of csv.writer(file) to a variable. The method writer_name.writerow(data_list) will either overrite existing text or add a row to the end based on the mode used.

**.csv** files can also be read to a dictionary. Similarly, a dictionary can be written to a **.csv** file. The csv.DictReader(file_name) method returns a list of each row in dictionary form. These rows can then be read and modified using dictionary methods. To write a dictionary to a csv file, we must open the file in **'w'** mode and assign the result of the csv.DictWriter(file_name, fieldnames=field_list) to a variable. The field_list should specify the name of the keys, or the column names. Then, we can assign these names using the writer_name.writeheader() and write the rows using writer_name.writerows(dictionary_name).

The most powerful way of reading and changing
**.csv** files is using the **pandas** module. First, we must import this module using 'import pandas as pd'. The name 'pd' simply makes it easier to repeatedly use the library, this can be any name. The pd.read_csv(file_name) call will return a pandas DataFrame version of the **.csv** file. This data can now be accessed using column names and varias pandas functions. Similarly, a DataFrame can be converted to a csv file with df_name.to_csv(file_name, index=False).

In [ ]:
import csv
import pandas as pd

# the file is opened in read mode
with open("sales_historical_cars.csv", newline='') as csvfile:
  reader = csv.reader(csvfile)
  rows = []
  # each row is added to the rows[] list
  for row in reader:
    rows.append(row)
  # the first two rows are printed
  print(rows[:2])

dictionary = [{"studentid": 11785, "name": "Sarah Sanders", "gpa": 3.4}, {"studentid": 12689, "name": "Casey Parks", "gpa": 2.7}, {"studentid": 11452, "name": "Aiden Reynolds", "gpa": 3.7}, {"studentid": 13254, "name": "Marie Moreau", "gpa": 4.0}, {"studentid": 15632, "name": "Andre Scott", "gpa": 3.2}]
field_names = ["studentid", "name", "gpa"]
# the file is opened in write mode
with open("students.csv", mode = 'w') as csvfile2:
  # writer is created using field names
  writer = csv.DictWriter(csvfile2, fieldnames=field_names)
  # header names are added to the file
  writer.writeheader()
  # rows added to file
  writer.writerows(dictionary)

# the csv is read to a DataFrame and displayed
df = pd.read_csv("students.csv")
df

[['region', 'category', 'parameter', 'mode', 'powertrain', 'year', 'unit', 'value'], ['Australia', 'Historical', 'EV sales', 'Cars', 'BEV', '2011', 'Vehicles', '49']]

   studentid            name  gpa
0      11785   Sarah Sanders  3.4
1      12689     Casey Parks  2.7
2      11452  Aiden Reynolds  3.7
3      13254    Marie Moreau  4.0
4      15632     Andre Scott  3.2

# Web Scraping

**Web scraping** is the process of automatically loading and extracting data from websites. To get content from any static webpage, we must first send an HTTP request to the site. For this, we must import the **requests** module. Then, to actually retrieve the content, we use the call requests.get(url). The method returns a response from the page that we assign to a variable.

Parsing information from a static webpage can be done using the BeautifulSoup library. This can be imported from the **bs4** module using 'from bs4 import BeautifulSoup'. Then, the HTML code can be parsed using BeautifulSoup(response.text, "html.parser"). Te reult of the previous method call, or the soup, is assigned to a variable. To make the soup more readable, we can the prettify() function. Or, to find content that matches a certain type, the find(tag) or find_all(tag) methods can be used. The number of elements can be specified in the find_all methhod.

In [ ]:
import requests
from bs4 import BeautifulSoup

# request is sent to the wikipedia page on the War of Roses
response = requests.get("https://en.wikipedia.org/wiki/War_of_the_Roses")
# BeautifulSoup parses the HTML data
soup = BeautifulSoup(response.text, "html.parser")
# we find and print the first 5 paragraphs in the page
paragraphs = soup.find_all("p")
for i in range(5):
  print(paragraphs[i].text)
# convert soup to text
text = soup.get_text()
# the major houses involved are Lancaster, York, and Tudor
lcount = text.count("Lancaster")
ycount = text.count("York")
tcount = text.count("Tudor")
print(f"Lancaster: {lcount}")
print(f"York: {ycount}")
print(f"Tudor: {tcount}")

The Wars of the Roses, known at the time and in following centuries as the Civil Wars, and also the Cousins' War, were a series of armed confrontations, machinations, battles and campaigns fought over control of the English throne from 1455 to 1487. The conflict was fought between supporters of the House of Lancaster and House of York, two rival cadet branches of the royal House of Plantagenet. The conflict resulted in the end of Lancaster's male line in 1471, leaving the Tudor family to inherit their claim to the throne through the female line. Conflict was largely brought to an end upon the union of the two houses through marriage, creating the Tudor dynasty that would subsequently rule England.

The Wars of the Roses were rooted in English socio-economic troubles caused by the Hundred Years' War (1337–1453) with France, as well as the quasi-military bastard feudalism resulting from the powerful duchies created by King Edward III. The mental instability of King Henry VI of the House of Lancaster revived his cousin Richard, Duke of York's interest in a claim to the throne. Warfare began in 1455 with York's capture of Henry at the First Battle of St Albans, upon which York was appointed Lord Protector by Parliament. Fighting resumed four years later when Yorkists led by Richard Neville, Earl of Warwick captured Henry again at the Battle of Northampton. After attempting to seize the throne, York was killed at the Battle of Wakefield, and his son Edward inherited his claim per the controversial Act of Accord. The Yorkists lost custody of Henry in 1461 after the Second Battle of St Albans, but defeated the Lancastrians at the Battle of Towton. The Yorkist Edward was formally crowned in June 1461.

In 1464, Edward married Elizabeth Woodville against the advice of Warwick, and reversed Warwick's policy of seeking closer ties with France. Warwick rebelled against Edward in 1469, leading to Edward's imprisonment after Warwick's supporters defeated a Yorkist army at the Battle of Edgcote. Edward was allowed to resume his rule after Warwick failed to replace him with his brother George of Clarence. Within a year, Warwick launched an invasion of England alongside Henry VI's wife Margaret of Anjou. Edward fled to Flanders, and Henry VI was restored as king in 1470. Edward mounted a counter-invasion with aid from Burgundy a few months later, and killed Warwick at the Battle of Barnet. Henry was returned to prison, and his sole heir later killed by Edward at the Battle of Tewkesbury, followed by Henry's own death in the Tower of London, possibly on Edward's orders. Edward ruled unopposed for the next twelve years, during which England enjoyed a period of relative peace. Upon his death in April 1483, he was succeeded by the twelve-year-old Edward V, who reigned for 78 days until being deposed by his uncle Richard III.

Richard assumed the throne amid controversies regarding the disappearance of Edward IV's two sons. He was met with a short-lived but major revolt and a wave of Yorkist defections. Amid the chaos, Henry Tudor, a descendant of Edward III through Lady Margaret Beaufort and a veteran Lancastrian, returned from exile with an army and defeated and killed Richard at Bosworth Field in 1485. Tudor then assumed the English throne as Henry VII and united the rival houses through marriage with Elizabeth of York, Edward IV's eldest daughter and heir. The wars concluded in 1487, with Henry VII's defeat of the remaining Yorkist opposition at Stoke Field. The House of Tudor would rule England until 1603, a period that saw the strengthening of the monarchy and the end of the medieval period in England.

Lancaster: 39
York: 235
Tudor: 94

To scrape from websites with multiple needed pages or with dynamic components, we can use the automation tool **Selenium**. It can help us find HTML elements matching certain features, take data from them, and interact with them. Thus, we can search by specific terms and navigate through a website to widen our scraping.

To webscrape using Selenium, we must first import the **webdriver**. Then, from the webdriver, we can import the **Keys**, **Service**, and **Options** modules. We can also import the **time** and **csv** libraries for extra functionality. We first initialize the service variable by assigning it the result of Service("chrome_driver_path"). Then, we assign webdriver.Chromer(service=service_var) to a driver variable. We specify the website we are targeting using driver.get("website_url").

To find an **HTML element** in the page, we can use driver.find_element(By.element_type, 'keyword/name'). This can further analyzed for text, elements, or links attached. To enter text into a **search** bar, we can find its associated element and use element.send_keys("search_text"). Similarly, to click a **button**, we can find the element using its HTML and call element.click(). To find specific **attributes** in the element, we can use element.get_attribute("attribute_name"). Between any actions that require loading, we can use time.sleep(x) or driver.implicitly_wait(0.5) to make sure verything reloads. When all of the scraping is finished, driver.quit() will end the automated session.

In [2]:
import csv
import pandas as pd

# below is the data scraped from dice.come/jobs
# the search is on machine learning engineer intern jobs in Massachusetts
df = pd.read_csv("dice_scraped.csv")
df

,Title,Company,Location,Date,Description,Link
0,Machine Learning Engineer,ServIT Consulting LLC,Remote,Today,Position: Machine Learning Engineer/Data Scien...,https://www.dice.com/job-detail/99f8e6a7-53c9-...
1,AI/Machine Learning Engineer,Sacrum Technologies LLC,Remote,Today,We are looking for a highly motivated and skil...,https://www.dice.com/job-detail/46fd424f-5f28-...
2,Machine Learning Engineer - Biologics R&D,"Judge Group, Inc.","Worcester, Massachusetts",Today,"Location: Worcester, MA Salary: $75.00 USD Hou...",https://www.dice.com/job-detail/5b3f5638-8944-...
3,AI/ML Engineer with .NET,AGUH INC,Remote,Today,Sr AI/MI Engineer and permanent residents. Rem...,https://www.dice.com/job-detail/6fe50c0f-67b2-...
4,Senior Machine Learning Engineer,General Motors,Remote or Hybrid,Today,Job Description Remote: This role is based rem...,https://www.dice.com/job-detail/71a8ee38-3df2-...
...,...,...,...,...,...,...
147,"Senior Machine Learning Modeler, Risk Automati...",Block Inc,Remote or California,Today,"Block is one company built from many blocks, a...",https://www.dice.com/job-detail/4d46487d-3846-...
148,Senior Data Scientist - ML,CVS Health,"Remote or Wellesley, Massachusetts",Today,"At CVS Health, we're building a world of healt...",https://www.dice.com/job-detail/90b855ad-fcee-...
149,Machine Learning Scientist II,Wayfair,"Boston, Massachusetts",Today,"Candidates for this position are to be based, ...",https://www.dice.com/job-detail/0887b53e-3477-...
150,AI/ ML Engineer,Resource 1,Remote,6d ago,Resource 1 is in need of an Artificial Intelli...,https://www.dice.com/job-detail/a9441770-a21b-...
151,Sr Technical Writer-Must have Machine Learning...,"Trilyon, Inc.",Remote,Today,"For over 15 years, Trilyon has been at the for...",https://www.dice.com/job-detail/bfc22176-f347-...

# Object-Oriented Concepts

Python is an **object-oriented** programming language. Thus, everything in Python is an **object**: strings, lists, dictionaries, ints. **Classes** are the blueprints for objects; they define the data contained within the object and the methods that can be used on it. To define a class, we use the class keyword and give it a name. The header will look like class Name:.

Within the body of body of the class, we can define variables and functions that each object created using it will have. Variables in the object are accessed using varname.property. The class's function can be called similarly, with varname.funcname(args). To modify the value kept in a variable in the object, we can use varname.property = new_value.

To create an object using a class, we assign the return value of ClassName(), an instance of the class, to a variable. This variable will be able to acccess the data and methods inside the class automatically. To delete properties from an object or the object itself, we use the **del** keyword.

In [ ]:
class Hello:
  greeting = "hello"

# assign an instance of Hello to a variable
hello_object = Hello()

# access and print the data
print(hello_object.greeting)

# we can modify the greeting attribute to "hi"
hello_object.greeting = "hi"
print(hello_object.greeting)

del hello_object

hello
hi

The current instance of the class, or the object, is automatically passed into any function call on it as the first parameter. Thus, we must account for this by adding a parameter for the object itself within each function in the class. Usually, this is done with a parameter name '**self**', but it does not matter.

In [ ]:
class Math:
  def sum(self, x, y):
    return x + y
  def difference(obj, x, y):
    return x - y
  def product(self, x, y):
    return x * y
  def quotient(name, x, y):
    return x / y

arithmetic = Math()
print(arithmetic.sum(10, 2))
print(arithmetic.difference(9, 3))
print(arithmetic.product(5, 4))
print(arithmetic.quotient(9, 2))

12
6
20
4.5

All classes have two in-built functions: __init__() and __str__(). The init functions is automatically called when an object of the class is created. This function assigns values to the object's attributes, or the data that change for each instance of the class. These values are passed into the constructor with ClassName(values). Then, in the init function, the properties can be initialized using self.varname = value.

The str() function returns the function's string representation. The default representation is the "<current_module.ClassName object at memory_address". To return a more readable string when printing an object of the class, we must define the __str__() function and specify the string it should return

In [ ]:

class Person:
  # while it is good practice to match the attribute names to the parameter names, his is not necessary
  def __init__(self, first_name, last_name, age):
    self.first_name = first_name
    self.last_name = last_name
    self.old = age

person_1 =  Person("Sierra", "James", 29)
print(person_1.first_name)
print(person_1.last_name)
print(person_1.old)
# the class has no defined __str__() function, so it will return the default
print(person_1)

# the Person2 class is identical to Person, except for its __str__() method
class Person2:
  def __init__(self, first_name, last_name, age):
    self.first_name = first_name
    self.last_name = last_name
    self.old = age
  def __str__(self):
    return f"{self.first_name} {self.last_name} is {self.old} years old"

person_2 = Person2("Sierra", "James", 29)
# this will print the specified string representation
print(person_2)

Sierra
James
29
<__main__.Person object at 0x7d1395ed6dd0>
Sierra James is 29 years old

To reuse code, we can also have '**child**' classes (or subclasses) which **inherit** functionality from another (**parent**/super) class. To create a child class, we must pass the parent class directly into the child class definition: class ChildName(ParentName):. The child class will automaticallly inherit all methods and data from the parent class.

To refine a method from the parent class, we can write the same method name in the child class to override the original code. Then, the parent class's code can be refrenced using the **super**().funcname() call. Below the call, additional code can be added to make the function more specific. If the parent code is not necessary at all, the super() method does not need to be called.

One child inheriting from a parent is **single inheritance**. If multiple children inherit from a single parent, that would instead be a case of **hierarchical inheritation**.

In [ ]:
class Animal:
  def __init__(self, species, name, age, gender):
    self.species = species
    self.name = name
    self.age = age
    self.gender = gender
  def __str__(self):
    return f"{self.name} is a {self.species} and is {self.age} years old"
  def speak(animal):
    return f"**sounds**"

# the child class Human inherits from Animal
class Human(Animal):
  # the init function calls super to initialize the species, first name, age, and gender
  # the unique parameters, last name and location, are initialized individually
  def __init__(self, first_name, last_name, age, country, gender):
    super().__init__("human", first_name, age, gender)
    self.last_name = last_name
    self.location = country
  # the str function adds to the inherited string for a more specific description
  def __str__(self):
    if self.gender == "male":
      return super().__str__() + f". He is from {self.location}"
    else:
      return super().__str__() + f". She lives in {self.location}"
  # the speak function does not use any of the original code
  def speak(person):
    return f"Hello, my name is {person.name}"

class Dog(Animal):
  # the init function calls super to initialize the species, first name, age, and gender
  # the unique parameters, breed and owner, are initialized individually
  def __init__(self, name, age, gender, breed, owner):
    super().__init__("dog", name, age, gender)
    self.breed = breed
    self.owner = owner
  # the str function adds to the inherited string for a more specific description
  def __str__(self):
    if self.gender == "male":
      return super().__str__() + f". He is a {self.breed} and his owner is {self.owner.name}. They live in {self.owner.location}"
    else:
      return super().__str__() + f". She is a {self.breed} and her owner is {self.owner.name}. They live in {self.owner.location}"
  # the speak function does not use any of the original code
  def speak(animal):
    return f"**bark bark**"

# this uses the parent data and functions
animal = Animal("dog", "Max", 5, "male")
print(animal)
print(animal.speak())

# this uses the human class data and functions
human_1 = Human("James", "Carter", 35, "USA", "male")
print(human_1)
print(human_1.speak())

# this uses the dog class data and functions
dog = Dog("Max", 5, "male", "Labrador", human_1)
print(dog)
# despite being the same species as the animal var, dog.speak() returns "*bark bark*"
# since it is a member of the Dog class and overrides the original method
print(dog.speak())

Max is a dog and is 5 years old
**sounds**
James is a human and is 35 years old. He is from USA
Hello, my name is James
Max is a dog and is 5 years old. He is a Labrador and his owner is James. They live in USA
**bark bark**

Method overriding in child classes is a form of **polymorphism**. This concept describes when a single function or operator has different behaviors based on the way it is used. The two types of polymorphism are **compile-time** and **run-time**.

**Compile-time** polymorphism allows methods or operators with the same name to function differently based its parameters or usage. For example, the **'+'** operator can add two numerical values or concatenate two strings, based on the way it is used.

**Run-time** polymorphism is when objects of different classes respond differently to the same function call. When a child class overrides a method in its parent class, it is decided at runtime that the child class's version of the method should be executed.

In [ ]:
def add(x, y):
  return x + y
print(add(1, 2))
print(add("hello", " world"))

3
hello world

Just like child class can inherit from a parent class, another class can inherit from it. This describes the concept of **multi-level inheritence**, a chain of classes inheriting from each other. This child class will inherit all data and methods from its parent class and all the information that the parent inherited from the grandparent class.

In [ ]:
class Student(Human):
  # the init function calls super to initialize the species, first name, age, and gender
  # the unique parameters, last name and location, are initialized individually
  def __init__(self, first_name, last_name, age, country, gender, student_id, gpa):
    super().__init__(first_name, last_name, age, country, gender)
    self.student_id = student_id
    self.gpa = gpa
  # the grandparent class method is used with super().super() to access the original __string__() method and add to it
  def __string__(self):
    if self.gender == "female":
      return super().super().__str__() + f". She is student {self.student_id} in {self.location} and her gpa is {self.gpa}"
    else:
      return super().super().__str__() + f". He is student {self.student_id} in {self.location} and her gpa is {self.gpa}"
  # this new method adds class-specific functionality
  def is_honor(self):
    if self.gpa > 3.5:
      return True
    else:
      return False

student3 = Student("Cassie", "Daniels", 16, "Candaa", "female", 12345, 4.0)
print(student3)
# even though the speak method is not defined in the Student class, it is inherited from human
print(student3.speak())
if student3.is_honor():
  print("This student is an honor student")

Cassie is a human and is 16 years old. She lives in Candaa
Hello, my name is Cassie
This student is an honor student

**Multiple inheritance** is when a child class inherits from multiple parents, gaining the data and methods of each of them. To inherit from multiple parent classes, they must de specified in the child class definition: class ClassName(Parent1, Parent2):.

Since there are multiple parent classes, super() calls only the first parent class named in the child class definition. Similarly, if there are two functions with the same names in both parent classes, calling the function on an object of the child class will use the first parent's version. This is due to the **Method Resolution Order (MRO)**, in which when a method not in the child class is called, its definition is searched for in the parent classes from left-to-right. The first definitions matching the name that is found is the one that is called. To overrride this preference for the first parent, we can mention another parent by name with the format: Parent2.func_name(child_object).

The **diamond inheritance problem** describes the only situation where the first parent is not automatically preffered. Assume for a class ClassD, its two classes, ClassB and ClassC, inherit a method func_1 from a parent ClassA. If func_1 is overriden in both ClascB and ClassC or only overriden in ClassB, ClassD will inherit ClassB's version of func_1. However, if func_1 is only overriden in ClassC, ClassD will inherit ClassC's version of the function. This is an example of hybrid inheritance, since it mixes different inheritance types: multi-level and multiple.

In [ ]:
class Parent1:
  def func_1(self):
    print("Parent 1")
  def func_2(self):
    print("Parent 1")
class Parent2:
  def func_1(self):
    print("Parent 2")
  def func_2(self):
    print("Parent 2")
class Child(Parent1, Parent2):
  # Parent2's version of func_2 is specfically called
  def func_2(self):
    Parent2.func_2(self)

obj = Child()
# since Parent1 is first in the class definition, it's version of func_1 is inherited
obj.func_1()
# Parent2's version of func_2 is used in the Child class override
obj.func_2()


class ClassA:
  def func_1(self):
    print("Class A")
  def func_2(self):
    print("Class A")
  def func_3(self):
    print("Class A")
  def func_4(self):
    print("Class A")
class ClassB(ClassA):
  def func_1(self):
    print("Class B")
  def func_2(self):
    print("Class B")
class ClassC(ClassA):
  def func_1(self):
    print("Class C")
  def func_3(self):
    print("Class C")
class ClassD(ClassB, ClassC):
  pass

obj = ClassD()
# since both classes override func_1, ClassB's version is printed
obj.func_1()
# since ClassB overrides func_2, its version is printed
obj.func_2()
# since ClassC overrides func_3, its version is printed
obj.func_3()
# since neither class overrides func_4, ClassA's version is printed
obj.func_4()

Parent 1
Parent 2
Class B
Class B
Class C
Class A

One of the core principles of object-oriented programming is **abstraction**. This describes the concept of hiding internal details and only allows necessary features to be shown. Abstraction can be completed using **abstract classes** and **abstract methods**. Abstract classes can only be base classes in Python, meaning they cannot inherit from other user-created classes. They also cannot be instantiated. Abstract methods, however, must be implemented/overriden in their child classes.

To create an abstract class, we must first import **'ABC'** and **'abstractmethod'** from the **abc** module. Any abstract method must have ABC as its only parent class. Within the body of the class, regular functions and abstract functions can both be defined. Normal functions will be inherited normally by children, but abstract methods must be overriden. Abstract methods are indicated with '**@abstractmethod** before the function definition. Within the abstract method body, there should only be the keyword **'pass'** to leave implementation for child classes.

If every method within an abstract class is also abstract, then it is **fully abstract**. Otherwise, there is only **partial abstraction**.

In [ ]:
from abc import ABC,abstractmethod

# this class is partially abstracted since it contains non-abstract methods
class Wings(ABC):
  @abstractmethod
  def canFly(self):
    pass
  @abstractmethod
  def canGlide(self):
    pass
  @abstractmethod
  def canSwim(self):
    pass
  def __str__(self):
    return f"This creature has wings."

# all abstract methods must be implemented in subclasses, regular functions can be overriden if wished
class FruitFly(Wings):
  def canFly(self):
    return True
  def canGlide(self):
    return True
  def canSwim(self):
    return True
  def __str__(self):
    return super().__str__() + f" It can fly, glide, and swim."

class SugarGlider(Wings):
  def canFly(self):
    return False
  def canGlide(self):
    return True
  def canSwim(self):
    return False
  def __str__(self):
    return f"This animal has membranes that mimic wings and can glide"

class Penguin(Wings):
  def canFly(self):
    return False
  def canGlide(self):
    return False
  def canSwim(self):
    return True
  def __str__(self):
    return super().__str__() + f" It can only swim."

fruitfly = FruitFly()
print(fruitfly)
if fruitfly.canFly():
  print("It can fly")
if fruitfly.canGlide():
  print("It can glide")
if fruitfly.canSwim():
  print("It can swim")

sugar = SugarGlider()
print(sugar)
if sugar.canFly():
  print("It can fly")
if sugar.canGlide():
  print("It can glide")
if sugar.canSwim():
  print("It can swim")

penguin = Penguin()
print(penguin)
if penguin.canFly():
  print("It can fly")
if penguin.canGlide():
  print("It can glide")
if penguin.canSwim():
  print("It can swim")

This creature has wings. It can fly, glide, and swim.
It can fly
It can glide
It can swim
This animal has membranes that mimic wings and can glide
It can glide
This creature has wings. It can only swim.
It can swim

Another important OOP concept is **encapsulation**, where data and the methods that use them are bundled into a single object: a class. Additionally, the access to this data is restricted to prevent it from being modified without necessary permission or misused and reduce complexity for the user.

**Public** attributes are defined as normal variables and are accessible everywhere. They can be directly accessed and modified using object.property = value.

By putting and underscore **'_'** before an attribute's name, we can make it a **protected** member. This data should only be accessed and modified within the class and its subclasses. While the variables can still be accessed and modified anywhere, the underscore is meant to discourage this.

The highest level of encapsulation is **private** data, which can only be accessed within the class itself. Members are made private by putting two underscores **'__'** before the property name. When these attributes are accessed, they raise an AttributeError. This is because they are renamed to _ClassName__var_name. The variable can still be modified using this new name, but it is meant to prevent this. To view and change the variable safely, the class should include getters and setters in the methods.

In [ ]:
class BankAccount():
  def __init__(self, name, balance):
    self.name = name
    # the balance is private, because it should not be modified without permission
    self.__balance = balance
  def deposit(self, amount):
    self.__balance += amount
  def withdraw(self, amount):
    self.__balance -= amount
  def get_balance(self):
    return self.__balance

account = BankAccount("Sarah Palin", 50)

# accessing the private variable directly will raise an error
try:
  account.__balance +=5
except AttributeError:
  account._BankAccount__balance += 5

print(f"balance: {account.get_balance()}")

balance: 55